#API config

server:
  port: 8081

# Database config

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concessionaire
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret: concessionaire
    issuer: Main
    ttlMillis: 1080000